### ISSUE TITLE
Air Sensors

### ISSUE THREAD

**Issue by CrispyButtermilkChickenSalad** [jmontineri/OpeNITHM#12]
Anybody else have issues getting the air sensors to work. Everything else works fine but the air sensors, which spit out "." constantly, and no other output listed (keys don't interfere). Not sure if i messed something up with "FastLED" or if I wired something incorrectly based on @pikapikahikaru's guide, considering they listed the wiring of the photoresistors opposite to the silkscreen of the pcb.
![image](https://user-images.githubusercontent.com/62200737/230518308-df9ea52d-1016-402e-baf9-c452386136b7.png)

If anybody could point me in the right direction to tackling this issue, it would be much appreciated.

**Comment by Yona-W** [comment]
Given the PCB, I'm assuming you're using something based on veroxzik's branch? I don't know the guide you're referring to, but make sure:
- You're connecting the sensor boards to the main board using the solder pads on the *opposite* side of the LEDs / phototransistors
- The LEDs and transistors are connected to the correct pins on the main board

The wiring as depicted on the image is correct. One side of the board has traces for the LEDs, and the other side has traces for the transistors. The through-holes aren't plated, so only the traces on whichever side you're soldering the leads are active. You insert the LEDs on the side with the traces meant for the phototransistors, so that you can solder them to the pads on the opposite side.

There should be 7 wires coming out of the phototransistor side, and 3 wires coming out of the LED side. If you have a multimeter, I'd suggest using it in condictivity mode to double-check your wiring and soldering.

**Comment by CrispyButtermilkChickenSalad** [comment]
Thanks for the feedback, I've only just gotten around to double checking my wiring (where I found the image above to be right -_-). I've rewired everything based on the pcb schematics provided in the main repo and have messed with the AIR_INPUT_DETECTION value to no avail. I'm pretty sure it's a firmware issue now after sanity checking all my wiring a few times over. I could give some ideas of where I could have gone wrong, such as modifying the files of the libraries needed, as I'm not the most familiar with the Arduino IDE. Any pointers for going over checking that I've downloaded the firmware/checking the IR outputs would be lovely ('m not sure if there's something in the config file that explicitly allows me to monitor the IR outputs, only the keys).
